# Generated by Django 5.1.2 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_alter_profile_role_alter_review_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(default='No feedback provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
