# Generated by Django 5.1.2 on 2024-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_tutorprofile_weekly_hours_alter_review_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
