# Generated by Django 5.1.2 on 2024-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_remove_tutorprofile_location_tutorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
