# Generated by Django 5.1.2 on 2024-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_tutorprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
