# Generated by Django 5.1.2 on 2024-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_tutorprofile_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='school_level',
            field=models.CharField(blank=True, help_text='Comma-separated list of school levels', max_length=255, null=True),
        ),
    ]
