# Generated by Django 5.1.2 on 2024-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
